pipeline {
    agent any

    stages {

        stage('Build Backend') {
            steps {
                dir('Backend') {   // ✅ IMPORTANT FIX
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Backend') {   // ✅ IMPORTANT
                    bat 'docker-compose build'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Backend') {   // ✅ IMPORTANT
                    bat 'docker-compose down'
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}