server:
  port: 8079

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://localhost:3307/auth_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  jwt:
    issuer: clinic-auth-service
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_MIN_32_CHARS"
    expiration-minutes: 60

bootstrap:
  admin:
    email: admin@gmail.com
    password: Admin@123