spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8191}

# ✅ Common settings (shared across all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health,info

# ✅ Eureka config (common)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

# ✅ Internal communication security (custom header)
app:
  internal-key: ${INTERNAL_SECRET}
