server:
  port: 8191

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://localhost:3307/auth_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "MDEyMzQ1Njc4OWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHg="
  expiry-ms: 3600000  # 1 hour

app:
  # Used in AuthService for internal API security
  internal-key: "CLINIC_INTERNAL_SECRET"

