spring:
  application:
    name: diagnostic-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8073}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

app:
  internal-key: ${INTERNAL_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info